# Generated by Django 5.1.4 on 2024-12-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_product_remove_order_quantity_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
